version: '3.4'
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    user: root
    ports:
      - "14300:1433"
    environment:
      MSSQL_SA_PASSWORD: "SqlPassw0rd!"
      ACCEPT_EULA: "Y"
    container_name: "sql2019"
    hostname: sql1
  

  webapp:
    build:
      context: .
      dockerfile: "Unik.Webapp/Dockerfile"
    container_name: "webapp"
    ports: 
      - "8080:80"
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ConnectionStrings:UserDb": "Server=db;Database=Unik.WebAppUsers;Trusted_Connection=True;MultipleActiveResultSets=true;TrustServerCertificate=True"
      "UnikBaseUrl": "https://unik.api"
    depends_on:
      - db
      - unik.api
  

  unik.api:
    ports:
      - "3230:80"
    build:
      context: .
      dockerfile: "Unik.Api/Dockerfile"
    container_name: "unik.api"
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "ConnectionStrings:UnikConnection" : "Server=db;Database=Unik;Trusted_Connection=True;MultipleActiveResultSets=true;User id=SA;Password=SqlPassw0rd!;TrustServerCertificate=True;"
    depends_on: 
      - db 


# networks:
#   unik_network:
#     name: unik_network
